# Generated by Django 4.2.1 on 2023-05-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchid', models.CharField(max_length=20)),
                ('branchname', models.CharField(max_length=20)),
                ('locationid', models.CharField(max_length=20)),
                ('doornumber', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('emailid', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField(max_length=20)),
                ('faxnumber', models.IntegerField(max_length=20)),
            ],
            options={
                'db_table': 'Branch',
            },
        ),
    ]
