# Generated by Django 4.2.1 on 2023-05-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_branch_faxnumber_alter_branch_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='faxnumber',
            new_name='faxnum',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='phonenumber',
            new_name='phonenum',
        ),
    ]
