# Generated by Django 4.2.1 on 2023-05-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customermanager_alter_user_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='locationid',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='customermanager',
            table='cm',
        ),
    ]
