# Generated by Django 4.2.1 on 2023-05-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_branch_locationid_alter_customermanager_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customermanager',
            table='customermanager',
        ),
    ]
