# Generated by Django 4.2.1 on 2023-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_customermanager_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingmanager',
            fields=[
                ('bookingid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customerid', models.CharField(max_length=50)),
                ('itemdescription', models.CharField(max_length=50)),
                ('noofbundles', models.IntegerField()),
                ('weight', models.CharField(max_length=50)),
                ('pickuptype', models.CharField(max_length=50)),
                ('deliverytype', models.CharField(max_length=50)),
                ('dateofbooking', models.DateField()),
                ('pickupbranch', models.CharField(max_length=50)),
                ('deliverybranch', models.CharField(max_length=50)),
                ('pickupaddress', models.CharField(max_length=50)),
                ('deliveryaddress', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
