# Generated by Django 4.2.1 on 2023-05-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_bookingmanager'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingmanager',
            table='Bookingmanager',
        ),
    ]
