# Generated by Django 4.2.1 on 2023-05-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_customermanager_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingmanager',
            table='table2',
        ),
        migrations.AlterModelTable(
            name='customermanager',
            table='table1',
        ),
    ]
