# Generated by Django 4.2.1 on 2023-05-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_bookingmanager_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingmanager',
            table='Bookingmanager',
        ),
    ]
