# Generated by Django 4.2.1 on 2023-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_bookingmanager_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.CharField(max_length=50)),
                ('customerid', models.CharField(max_length=50)),
                ('itemdescription', models.CharField(max_length=50)),
                ('noofbundles', models.IntegerField()),
                ('weight', models.CharField(max_length=50)),
                ('pickuptype', models.CharField(max_length=50)),
                ('deliverytype', models.CharField(max_length=50)),
                ('dateofbooking', models.DateField()),
                ('pickupbranch', models.CharField(max_length=50)),
                ('deliverybranch', models.CharField(max_length=50)),
                ('pickupaddress', models.CharField(max_length=50)),
                ('deliveryaddress', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.DeleteModel(
            name='Bookingmanager',
        ),
    ]
