# Generated by Django 4.2.1 on 2023-05-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_booking_delete_bookingmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customermanager',
        ),
    ]
