# Generated by Django 4.2.1 on 2023-05-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_customermanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Book',
        ),
    ]
