# Generated by Django 4.2.1 on 2023-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_book_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookingid',
            field=models.Field(max_length=50, primary_key=True, serialize=False),
        ),
    ]
