# Generated by Django 4.2.1 on 2023-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_book_bookingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookingid',
            field=models.Field(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
